config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users
  get "home/about" => "homes#about"
  resources :books, only: [:index, :show, :edit, :update, :create, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :user_id, uniqueness: { scope: :book_id, message: "You have already liked this post." }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_one_attached :profile_image
  
  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  validate :profile_image_format
  
  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  private

  def profile_image_format
    if profile_image.attached? && !profile_image.image?
      errors.add(:profile_image, 'must be a JPEG image')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?
   
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
   
  def after_sign_out_path_for(resource)
    root_path
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    comment = current_user.book_comments.find(params[:id])
    comment.destroy
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @new_book = @book  # エラーメッセージを表示するために @new_book に設定
      @books = Book.all
      @user = current_user
      render :index
    end
  end
  
  
  def index
    @books = Book.all
    @user = current_user
    @new_book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = current_user
    @new_book = Book.new
    @book_comment = BookComment.new
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def edit
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
    
    @book = Book.find(params[:id])
  end
  
  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(book.id)
    else
      @book = book
      render :edit
    end
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @new_book = Book.new
  end
  
  def edit
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
    @user = User.find(params[:id])
  end
  
  def update
    user = User.find(params[:id])
    if user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(user.id)
    else
      @user = user
      render :edit
    end
  end
  
  def index
    @new_book = Book.new
    @users = User.all
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
  <h2 class="mb-1">Books</h2>

    <table class="table table-hover table-inverse">
      <thead style="padding:12px;">
        <th style="width:104px;"></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </thead>
      <tbody>
        <% books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image(80, 80) %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
          </td>
          <td>
            <%= book.body %>
          </td>
          <td>
            <% if book.favorited_by?(current_user) %>
              <%= link_to book_favorites_path(book), method: :delete do %>
                <i class="fa-solid fa-heart" style="color: #ff3f0f;"></i>
                <span style="color: #ff3f0f;"><%= book.favorites.count %></span>
              <% end %>
            <% else %>
              <%= link_to book_favorites_path(book), method: :post do %>
                <i class="fa-solid fa-heart" style="color: #00ccff;"></i>
                <span style="color: #00ccff;"><%= book.favorites.count %></span>
              <% end %>
            <% end %>
          </td>
          <td>
            <p>コメント数: <%= book.book_comments.count %></p>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>

app/views/books/_new.html.erb
  <h2 class="mb-1">User info</h2>
  <%= image_tag user.get_profile_image(100,100) %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog" aria-hidden="true"></i>
    <% end %>
  </div>
  <h2 class="mt-3">New book</h2>
  <%= form_with model: book do |f| %>
    <div class="form-group">
      <label for="book_title">Title</label>
      <%= f.text_field :title, id: "book_title" %>
    </div>
    <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body, id: "book_opinion" %>
    </div>
    <div class="form-group">
      <%= f.submit 'Create Book', class: "btn btn-success" %>
    </div>
  <% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label for="book_title">Name</label>
          <%= f.text_field :title, autofocus: true, id: "book_title", class: "form-control" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, id: "book_opinion" , class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class: "btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @new_book.errors.any? %>
  <%= @new_book.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% @new_book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render'new',user: current_user, book: @new_book%>
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render 'list', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'new', user: @book.user, book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user.id) do %> 
                  <%= image_tag @book.user.get_profile_image(100, 75) %><br>
                  <%= @book.user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(@book.id) do %>
                  <%= @book.title %>
                <% end %>
              </td>
              <td>
                <%= @book.body %>
              </td>
              <% if @book.user == current_user %>
              <td>
                <%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %>
              </td>
              <td>
                <%= link_to "Destroy",book_path(@book.id), method: :delete, class: "btn btn-sm btn-danger", data: { confirm: "Are you sure you want to delete this book?" } %>
              </td>
              <td>
                <% if @book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(@book), method: :delete do %>
                    <i class="fa-solid fa-heart" style="color: #ff3f0f;"></i>
                    <span style="color: #ff3f0f;"><%= @book.favorites.count %></span>
                  <% end %>
                <% else %>
                  <%= link_to book_favorites_path(@book), method: :post do %>
                    <i class="fa-solid fa-heart" style="color: #00ccff;"></i>
                    <span style="color: #00ccff;"><%= @book.favorites.count %></span>
                  <% end %>
                <% end %>
              </td>
              <td>
                <p>コメント数: <%= @book.book_comments.count %></p>
              </td>
              <% end %>
            </tr>
          </tbody>
        </table>
        <% @book.book_comments.each do |book_comment| %>
          <div class="d-flex">
            <%= link_to user_path(book_comment.user_id) do %>
              <%= image_tag book_comment.user.get_profile_image(100,100) %>
              <p><%= book_comment.user.name %></p>
            <% end %>
            <div class="ml-3">
              <%= book_comment.comment %>
              <% if book_comment.user == current_user %>
                <%= link_to "Destroy",book_book_comment_path(book_id: @book.id, id: @user.book_comments.last.id), method: :delete, class: "btn btn-sm btn-danger" %>
              <% end %>
            </div>
          </div>
        <% end %>
        <div>
          <%= form_with model: [@book, @book_comment] do |f| %>
            <%= f.text_area :comment, class: "form-control", rows: '5', placeholder: "コメントをここに" %>
            <%= f.submit "送信する", class: "mt-2" %>
          <% end %>
        </div>
    </div>
  </div>
</div>

    
    

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong> !!</h1>
      <p>In <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong>，</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" do %>Log in<% end %>
        </div>
        <div class="row">
          <%= link_to new_user_registration_path, class: "btn btn-success btn-sm btn-block mb-3 sign_up" do %>Sign up<% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/429d010fb7.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="padding: 8px 16px;">
        <div class="container mx-5 px-2">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li style="padding: 8px;">
                  <%= link_to user_path(current_user.id), class: "navbar-link text-light" do%>
                    <i class="fas fa-home" aria-hidden="true"></i> Home
                  <% end %>
                </li>
                <li style="padding: 8px;">
                  <%= link_to users_path, class: "navbar-link text-light" do %>
                    <i class="fas fa-users" aria-hidden="true"></i> Users
                  <% end %>
                </li>
                <li style="padding: 8px;">
                  <%= link_to books_path, class: "navbar-link text-light" do %>
                    <i class="fas fa-book-open" aria-hidden="true"></i> Books
                  <% end %>
                </li>
                <li style="padding: 8px;">
                  <%= link_to destroy_user_session_path, method: :delete, class: "navbar-link text-light" do %>
                    <i class="fas fa-sign-out-alt" aria-hidden="true"></i> Log out
                  <% end %>
                </li>
              <% else %>
                <li style="padding: 8px;">
                  <%= link_to root_path, class: "navbar-link text-light" do%>
                    <i class="fas fa-home" aria-hidden="true"></i> Home
                  <% end %>
                </li>
                <li style="padding: 8px;">
                  <%= link_to home_about_path, class: "navbar-link text-light" do %>
                    <i class="fas fa-link" aria-hidden="true"></i> About
                  <% end %>
                </li>
                <li style="padding: 8px;">
                  <%= link_to new_user_registration_path, class: "navbar-link text-light"  do %>
                    <i class="fas fa-user-plus" aria-hidden="true"></i> Sign up
                  <% end %>
                </li>
                <li style="padding: 8px;">
                  <%= link_to new_user_session_path, class: "navbar-link text-light" do %>
                    <i class="fas fa-sign-in-alt" aria-hidden="true"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    

  </header>
  <main style="margin:0 20px;">
    <p style="margin_bottom:16px;"><%= flash[:notice] %></p>
    <%= yield %>
  </main>
  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto"><p>CopyRight Infratop.inc</p></div>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, autofocus: true, id: "user_name", class: "form-control" %>
        </div>
        <div class="form-group">
          <label for="inputImage">Image</label>
          <%= f.file_field :profile_image, accept: "image/*", id: "inputImage", class: "form-control-file" %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, id: "user_introduction" , class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User', class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render'books/new', user: current_user, book: @new_book%>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2 class="mb-1">Books</h2>
  
      <table class="table">
        <thead style="padding:12px;">
          <th>image</th>
          <th>name</th>
          <th></th>
          <th colspan="3"></th>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= image_tag user.get_profile_image(100, 100) %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= link_to "Show", user_path(user.id) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render'books/new', user: @user, book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render'books/list', books: @books %>
    </div>
  </div>
</div>